# Generated by Django 5.1.2 on 2025-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("TOTAL_ACCESS", "Acceso Total (Admin Sistema)"),
                    ("CLINICAL_FULL", "Clínico Full (Médicos/Matronas)"),
                    ("CLINICAL_SUPPORT", "Clínico Apoyo (Enfermeras/TENS)"),
                    ("ADMINISTRATIVE", "Administrativo (Admisión/Estadística)"),
                    ("READ_ONLY", "Solo Lectura (Auditoría)"),
                ],
                default="RESTRICTED",
                max_length=25,
            ),
        ),
    ]
