# Generated by Django 5.1.2 on 2025-12-08 19:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VistaEstadisticasRnMensual",
            fields=[
                (
                    "mes",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("total_rn", models.IntegerField()),
                ("peso_promedio", models.IntegerField()),
                (
                    "edad_gestacional_promedio",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("rn_bajo_peso", models.IntegerField()),
                ("rn_apgar_bajo", models.IntegerField()),
                ("rn_con_malformacion", models.IntegerField()),
            ],
            options={
                "verbose_name": "Estadísticas RN mensuales",
                "verbose_name_plural": "Estadísticas RN mensuales",
                "db_table": "vista_estadisticas_rn_mensual",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaIndicadoresCalidadMensual",
            fields=[
                (
                    "mes",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("total_partos", models.IntegerField()),
                (
                    "porc_ligadura_tardia",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porc_contacto_piel",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porc_lactancia_temprana",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porc_alojamiento_conjunto",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porc_control_prenatal",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Indicadores de calidad mensuales",
                "verbose_name_plural": "Indicadores de calidad mensuales",
                "db_table": "vista_indicadores_calidad_mensual",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VistaRemMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=7)),
                ("rut_paciente", models.CharField(max_length=12)),
                ("nombre_completo", models.CharField(max_length=255)),
                ("edad_materna_parto", models.PositiveSmallIntegerField()),
                ("tipo_parto", models.CharField(max_length=50)),
                ("sexo_rn", models.CharField(max_length=15)),
                ("peso_gramos", models.IntegerField()),
                ("edad_gestacional_semanas", models.IntegerField()),
                ("apgar1", models.IntegerField()),
                ("apgar5", models.IntegerField()),
                ("ligadura_tardia_cordon", models.BooleanField()),
                ("contacto_piel_piel", models.BooleanField()),
                ("lactancia_primera_hora", models.BooleanField()),
                ("alojamiento_conjunto", models.BooleanField()),
                ("control_prenatal", models.BooleanField()),
            ],
            options={
                "verbose_name": "Vista REM mensual",
                "verbose_name_plural": "Vista REM mensual",
                "db_table": "vista_rem_mensual",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nacionalidad",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=60, unique=True, verbose_name="Nombre"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Nacionalidad",
                "verbose_name_plural": "Nacionalidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PuebloOriginario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Pueblo originario"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Pueblo originario",
                "verbose_name_plural": "Pueblos originarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoParto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tipo de parto"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de parto (catálogo)",
                "verbose_name_plural": "Tipos de parto (catálogo)",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120,
                        unique=True,
                        verbose_name="Nombre del consultorio",
                    ),
                ),
                (
                    "comuna",
                    models.CharField(blank=True, max_length=60, verbose_name="Comuna"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["activo"], name="idx_consultorio_activo")
                ],
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellido paterno"
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellido materno"
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre completo"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soltera", "Soltera"),
                            ("casada", "Casada"),
                            ("viuda", "Viuda"),
                            ("divorciada", "Divorciada"),
                            ("conviviente", "Conviviente"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "nivel_educacional",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ninguna", "Ninguna"),
                            ("basica", "Básica"),
                            ("media", "Media"),
                            ("tecnica", "Técnica"),
                            ("universitaria", "Universitaria"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Nivel educacional",
                    ),
                ),
                (
                    "consultorio_otro",
                    models.CharField(
                        blank=True,
                        help_text="Llenar solo si el consultorio no aparece en la lista.",
                        max_length=120,
                        verbose_name="Especifique Consultorio",
                    ),
                ),
                (
                    "nacionalidad_otro",
                    models.CharField(
                        blank=True,
                        help_text="Llenar solo si seleccionó 'Otra' en Nacionalidad.",
                        max_length=60,
                        verbose_name="Especifique Nacionalidad",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "estado_atencion",
                    models.CharField(
                        choices=[
                            ("en_espera", "En espera"),
                            ("en_observacion", "En observación"),
                            ("atendido", "Atendido"),
                            ("derivado", "Derivado"),
                        ],
                        default="en_espera",
                        max_length=20,
                        verbose_name="Estado de atención",
                    ),
                ),
                (
                    "riesgo_obstetrico",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                        ],
                        default="bajo",
                        max_length=10,
                        verbose_name="Riesgo obstétrico",
                    ),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Nombre contacto de emergencia",
                    ),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono contacto de emergencia",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "consultorio",
                    models.ForeignKey(
                        blank=True,
                        db_column="consultorio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes",
                        to="clinica.consultorio",
                        verbose_name="Consultorio de referencia",
                    ),
                ),
                (
                    "nacionalidad",
                    models.ForeignKey(
                        blank=True,
                        db_column="nacionalidad_codigo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes",
                        to="clinica.nacionalidad",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "pueblo_originario",
                    models.ForeignKey(
                        blank=True,
                        db_column="pueblo_originario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes",
                        to="clinica.pueblooriginario",
                        verbose_name="Pueblo originario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nombres", "apellido_paterno", "apellido_materno"],
            },
        ),
        migrations.CreateModel(
            name="HistorialPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("campo_modificado", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="clinica.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CasoClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("resumen", models.TextField(verbose_name="Resumen")),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_estudio", "En estudio"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "medico_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos_clinicos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico responsable",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casos_clinicos",
                        to="clinica.paciente",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso clínico",
                "verbose_name_plural": "Casos clínicos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(verbose_name="Fecha y hora del parto"),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha y hora de ingreso"
                    ),
                ),
                (
                    "posicion_parto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("semisentada", "Semisentada"),
                            ("sentada", "Sentada"),
                            ("litotomia", "Litotomía"),
                            ("cuadrupeda", "Cuadrúpeda"),
                            ("de_pie", "De pie"),
                            ("cuclilla", "Cuclilla"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Posición durante el parto",
                    ),
                ),
                (
                    "posicion_parto_otro",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Detalle de posición (si 'Otro')",
                    ),
                ),
                (
                    "sala",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sala / pabellón"
                    ),
                ),
                (
                    "edad_materna_parto",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Edad materna al parto",
                    ),
                ),
                (
                    "paridad",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Paridad"
                    ),
                ),
                (
                    "control_prenatal",
                    models.BooleanField(default=True, verbose_name="Control prenatal"),
                ),
                (
                    "preeclampsia_severa",
                    models.BooleanField(
                        default=False, verbose_name="Preeclampsia severa"
                    ),
                ),
                (
                    "eclampsia",
                    models.BooleanField(default=False, verbose_name="Eclampsia"),
                ),
                ("sepsis", models.BooleanField(default=False, verbose_name="Sepsis")),
                (
                    "infeccion_ovular",
                    models.BooleanField(default=False, verbose_name="Infección ovular"),
                ),
                (
                    "detalle_otra_patologia",
                    models.TextField(blank=True, verbose_name="Otras patologías"),
                ),
                (
                    "ligadura_tardia_cordon",
                    models.BooleanField(
                        default=False, verbose_name="Ligadura tardía del cordón"
                    ),
                ),
                (
                    "contacto_piel_piel",
                    models.BooleanField(
                        default=False, verbose_name="Contacto piel con piel"
                    ),
                ),
                (
                    "duracion_contacto_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duración contacto piel con piel (min)",
                    ),
                ),
                (
                    "lactancia_primera_hora",
                    models.BooleanField(
                        default=False, verbose_name="Lactancia en primera hora"
                    ),
                ),
                (
                    "alojamiento_conjunto",
                    models.BooleanField(
                        default=False, verbose_name="Alojamiento conjunto"
                    ),
                ),
                (
                    "vdrl_positivo",
                    models.BooleanField(default=False, verbose_name="VDRL positivo"),
                ),
                (
                    "hepatitis_b_positivo",
                    models.BooleanField(
                        default=False, verbose_name="Hepatitis B positivo"
                    ),
                ),
                (
                    "vih_positivo",
                    models.BooleanField(default=False, verbose_name="VIH positivo"),
                ),
                (
                    "complicaciones",
                    models.TextField(blank=True, verbose_name="Complicaciones"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "duracion_trabajo_parto_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(2880)],
                        verbose_name="Duración del trabajo de parto (min)",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partos",
                        to="clinica.paciente",
                        verbose_name="Madre",
                    ),
                ),
                (
                    "personal_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesional responsable",
                    ),
                ),
                (
                    "tipo_parto",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipo_parto_id",
                        help_text="Referencia a catálogo nacional de tipos de parto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episodios",
                        to="clinica.tipoparto",
                        verbose_name="Tipo de parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parto",
                "verbose_name_plural": "Partos",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Alta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(verbose_name="Fecha y hora de alta"),
                ),
                (
                    "tipo_alta",
                    models.CharField(
                        choices=[
                            ("medica", "Alta médica"),
                            ("traslado", "Traslado"),
                            ("fallecimiento", "Fallecimiento"),
                            ("otro", "Otro"),
                        ],
                        default="medica",
                        max_length=20,
                        verbose_name="Tipo de alta",
                    ),
                ),
                (
                    "condicion_egreso",
                    models.TextField(verbose_name="Condición al egreso"),
                ),
                (
                    "requiere_seguimiento",
                    models.BooleanField(
                        default=False, verbose_name="Requiere seguimiento"
                    ),
                ),
                (
                    "proxima_cita",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de próxima cita / control",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones adicionales"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "profesional_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="altas_emitidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesional responsable",
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alta",
                        to="clinica.parto",
                        verbose_name="Parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alta clínica",
                "verbose_name_plural": "Altas clínicas",
                "ordering": ["-fecha_alta"],
            },
        ),
        migrations.CreateModel(
            name="RecienNacido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Identificador interno"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("I", "Indeterminado"),
                        ],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "peso_gramos",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(400),
                            django.core.validators.MaxValueValidator(6500),
                        ],
                        verbose_name="Peso (g)",
                    ),
                ),
                (
                    "talla_cm",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(65),
                        ],
                        verbose_name="Talla (cm)",
                    ),
                ),
                (
                    "perimetro_cefalico_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Perímetro cefálico (cm)",
                    ),
                ),
                (
                    "apgar1",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="APGAR al minuto 1",
                    ),
                ),
                (
                    "apgar5",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="APGAR al minuto 5",
                    ),
                ),
                (
                    "edad_gestacional_semanas",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="Edad gestacional (semanas)",
                    ),
                ),
                (
                    "fecha_control_7_dias",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha control 7 días"
                    ),
                ),
                (
                    "fecha_control_28_dias",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha control 28 días"
                    ),
                ),
                (
                    "reanimacion",
                    models.CharField(
                        choices=[
                            ("Ninguna", "Ninguna"),
                            ("Básica", "Básica"),
                            ("Avanzada", "Avanzada"),
                        ],
                        default="Ninguna",
                        max_length=15,
                        verbose_name="Reanimación",
                    ),
                ),
                (
                    "tiene_malformacion",
                    models.BooleanField(
                        default=False, verbose_name="Presenta malformación"
                    ),
                ),
                (
                    "malformacion_detalle",
                    models.TextField(blank=True, verbose_name="Detalle malformación"),
                ),
                (
                    "condicion_inicial",
                    models.TextField(blank=True, verbose_name="Condición inicial"),
                ),
                (
                    "derivacion",
                    models.TextField(blank=True, verbose_name="Derivación / destino"),
                ),
                (
                    "diagnostico_alta",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Diagnóstico de alta"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        db_column="episodio_parto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recien_nacidos",
                        to="clinica.parto",
                        verbose_name="Episodio de parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recién nacido",
                "verbose_name_plural": "Recién nacidos",
                "ordering": ["parto", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventoClinicoRN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("Profilaxis Ocular", "Profilaxis ocular"),
                            ("Vacuna Hepatitis B", "Vacuna Hepatitis B"),
                            ("Vacuna BCG", "Vacuna BCG"),
                            ("Tamizaje Auditivo", "Tamizaje auditivo"),
                            ("Tamizaje PKU/TSH", "Tamizaje PKU/TSH"),
                            ("Tamizaje Cardiopatías", "Tamizaje cardiopatías"),
                        ],
                        max_length=40,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Resultado"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recien_nacido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_clinicos",
                        to="clinica.reciennacido",
                        verbose_name="Recién nacido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento clínico RN",
                "verbose_name_plural": "Eventos clínicos RN",
            },
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["fecha_nacimiento"], name="idx_paciente_fecha_nac"
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["nombres", "apellido_paterno"], name="idx_paciente_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="reciennacido",
            index=models.Index(fields=["peso_gramos"], name="idx_rn_peso"),
        ),
        migrations.AddIndex(
            model_name="reciennacido",
            index=models.Index(
                fields=["edad_gestacional_semanas"], name="idx_rn_edad_gest"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoclinicorn",
            constraint=models.UniqueConstraint(
                fields=("recien_nacido", "tipo_evento"), name="uq_evento_por_rn"
            ),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(fields=["fecha_hora"], name="idx_parto_fecha"),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(fields=["paciente"], name="idx_parto_paciente"),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(
                fields=["edad_materna_parto"], name="idx_parto_edad_materna"
            ),
        ),
    ]
