# Generated by Django 5.1.2 on 2025-11-16 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(verbose_name="Fecha y hora del parto"),
                ),
                (
                    "tipo_parto",
                    models.CharField(
                        choices=[
                            ("vaginal", "Vaginal"),
                            ("cesarea", "Cesárea"),
                            ("instrumental", "Instrumental"),
                            ("otro", "Otro"),
                        ],
                        default="vaginal",
                        max_length=20,
                        verbose_name="Tipo de parto",
                    ),
                ),
                (
                    "sala",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sala / pabellón"
                    ),
                ),
                (
                    "complicaciones",
                    models.TextField(blank=True, verbose_name="Complicaciones"),
                ),
                (
                    "duracion_trabajo_parto_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duración del trabajo de parto (min)",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partos",
                        to="clinica.paciente",
                        verbose_name="Madre",
                    ),
                ),
                (
                    "personal_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesional responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parto",
                "verbose_name_plural": "Partos",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
