# Generated by Django 5.1.2 on 2025-11-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_parto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecienNacido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        max_length=20, verbose_name="Identificador del RN"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("peso_gramos", models.PositiveIntegerField(verbose_name="Peso (g)")),
                ("talla_cm", models.PositiveIntegerField(verbose_name="Talla (cm)")),
                (
                    "apgar_1_min",
                    models.PositiveSmallIntegerField(verbose_name="APGAR 1 min"),
                ),
                (
                    "apgar_5_min",
                    models.PositiveSmallIntegerField(verbose_name="APGAR 5 min"),
                ),
                (
                    "condicion_inicial",
                    models.TextField(blank=True, verbose_name="Condición inicial"),
                ),
                (
                    "derivacion",
                    models.TextField(blank=True, verbose_name="Derivación / destino"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recien_nacidos",
                        to="clinica.parto",
                        verbose_name="Parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recién nacido",
                "verbose_name_plural": "Recién nacidos",
                "ordering": ["parto", "identificador"],
            },
        ),
    ]
