# Generated by Django 5.1.2 on 2025-11-16 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0003_reciennacido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(verbose_name="Fecha y hora de alta"),
                ),
                (
                    "tipo_alta",
                    models.CharField(
                        choices=[
                            ("medica", "Alta médica"),
                            ("traslado", "Traslado"),
                            ("fallecimiento", "Fallecimiento"),
                            ("otro", "Otro"),
                        ],
                        default="medica",
                        max_length=20,
                        verbose_name="Tipo de alta",
                    ),
                ),
                (
                    "condicion_egreso",
                    models.TextField(
                        help_text="Describir el estado clínico de madre y RN al momento del alta.",
                        verbose_name="Condición al egreso",
                    ),
                ),
                (
                    "requiere_seguimiento",
                    models.BooleanField(
                        default=False, verbose_name="Requiere seguimiento"
                    ),
                ),
                (
                    "proxima_cita",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de próxima cita / control",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones adicionales"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alta",
                        to="clinica.parto",
                        verbose_name="Parto",
                    ),
                ),
                (
                    "profesional_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="altas_emitidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesional responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alta clínica",
                "verbose_name_plural": "Altas clínicas",
                "ordering": ["-fecha_alta"],
            },
        ),
    ]
