# Generated by Django 5.1.2 on 2025-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0004_alta"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soltera", "Soltera"),
                    ("casada", "Casada"),
                    ("viuda", "Viuda"),
                    ("divorciada", "Divorciada"),
                    ("conviviente", "Conviviente"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
                null=True,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="nacionalidad",
            field=models.CharField(
                blank=True,
                choices=[("chilena", "Chilena"), ("extranjera", "Extranjera")],
                default="chilena",
                max_length=20,
                null=True,
                verbose_name="Nacionalidad",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="nivel_educacional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ninguna", "Ninguna"),
                    ("basica", "Básica"),
                    ("media", "Media"),
                    ("tecnica", "Técnica"),
                    ("universitaria", "Universitaria"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
                null=True,
                verbose_name="Nivel Educacional",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="pueblo_originario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ninguno", "Ninguno"),
                    ("mapuche", "Mapuche"),
                    ("aymara", "Aymara"),
                    ("rapanui", "Rapa Nui"),
                    ("otro", "Otro"),
                ],
                default="ninguno",
                max_length=20,
                null=True,
                verbose_name="Pueblo Originario",
            ),
        ),
    ]
