# Generated by Django 5.1.2 on 2025-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0005_paciente_estado_civil_paciente_nacionalidad_y_mas"),
    ]

    operations = [
        migrations.AddField(
            model_name="parto",
            name="posicion_parto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("semisentada", "Semisentada"),
                    ("sentada", "Sentada"),
                    ("litotomia", "Litotomía"),
                    ("cuadrupeda", "Cuadrúpeda"),
                    ("de_pie", "De pie"),
                    ("cuclilla", "Cuclilla"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                verbose_name="Posición durante el parto",
            ),
        ),
        migrations.AddField(
            model_name="parto",
            name="posicion_parto_otro",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Detalle de posición (si 'Otro')",
            ),
        ),
    ]
