# Generated by Django 5.1.2 on 2025-11-20 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_parto_posicion_parto_parto_posicion_parto_otro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaEstadisticasRnMensual',
            fields=[
                ('mes', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('total_rn', models.IntegerField()),
                ('peso_promedio', models.IntegerField()),
                ('edad_gestacional_promedio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rn_bajo_peso', models.IntegerField()),
                ('rn_apgar_bajo', models.IntegerField()),
                ('rn_con_malformacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estadísticas RN mensuales',
                'verbose_name_plural': 'Estadísticas RN mensuales',
                'db_table': 'vista_estadisticas_rn_mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaIndicadoresCalidadMensual',
            fields=[
                ('mes', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('total_partos', models.IntegerField()),
                ('porc_ligadura_tardia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porc_contacto_piel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porc_lactancia_temprana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porc_alojamiento_conjunto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porc_control_prenatal', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Indicadores de calidad mensuales',
                'verbose_name_plural': 'Indicadores de calidad mensuales',
                'db_table': 'vista_indicadores_calidad_mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaRemMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('rut_paciente', models.CharField(max_length=12)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('edad_materna_parto', models.PositiveSmallIntegerField()),
                ('tipo_parto', models.CharField(max_length=50)),
                ('sexo_rn', models.CharField(max_length=15)),
                ('peso_gramos', models.IntegerField()),
                ('edad_gestacional_semanas', models.IntegerField()),
                ('apgar1', models.IntegerField()),
                ('apgar5', models.IntegerField()),
                ('ligadura_tardia_cordon', models.BooleanField()),
                ('contacto_piel_piel', models.BooleanField()),
                ('lactancia_primera_hora', models.BooleanField()),
                ('alojamiento_conjunto', models.BooleanField()),
                ('control_prenatal', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Vista REM mensual',
                'verbose_name_plural': 'Vista REM mensual',
                'db_table': 'vista_rem_mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del consultorio')),
                ('comuna', models.CharField(blank=True, max_length=60, verbose_name='Comuna')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoClinicoRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Profilaxis Ocular', 'Profilaxis ocular'), ('Vacuna Hepatitis B', 'Vacuna Hepatitis B'), ('Vacuna BCG', 'Vacuna BCG'), ('Tamizaje Auditivo', 'Tamizaje auditivo'), ('Tamizaje PKU/TSH', 'Tamizaje PKU/TSH'), ('Tamizaje Cardiopatías', 'Tamizaje cardiopatías')], max_length=40, verbose_name='Tipo de evento')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('resultado', models.CharField(blank=True, max_length=100, verbose_name='Resultado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento clínico RN',
                'verbose_name_plural': 'Eventos clínicos RN',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuebloOriginario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Pueblo originario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pueblo originario',
                'verbose_name_plural': 'Pueblos originarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de parto')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de parto (catálogo)',
                'verbose_name_plural': 'Tipos de parto (catálogo)',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombres', 'apellido_paterno', 'apellido_materno'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='reciennacido',
            options={'ordering': ['parto', 'id'], 'verbose_name': 'Recién nacido', 'verbose_name_plural': 'Recién nacidos'},
        ),
        migrations.RemoveField(
            model_name='reciennacido',
            name='apgar_1_min',
        ),
        migrations.RemoveField(
            model_name='reciennacido',
            name='apgar_5_min',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dv',
            field=models.CharField(blank=True, max_length=1, verbose_name='Dígito verificador'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='parto',
            name='alojamiento_conjunto',
            field=models.BooleanField(default=False, verbose_name='Alojamiento conjunto'),
        ),
        migrations.AddField(
            model_name='parto',
            name='contacto_piel_piel',
            field=models.BooleanField(default=False, verbose_name='Contacto piel con piel'),
        ),
        migrations.AddField(
            model_name='parto',
            name='control_prenatal',
            field=models.BooleanField(default=True, verbose_name='Control prenatal'),
        ),
        migrations.AddField(
            model_name='parto',
            name='detalle_otra_patologia',
            field=models.TextField(blank=True, verbose_name='Otras patologías'),
        ),
        migrations.AddField(
            model_name='parto',
            name='duracion_contacto_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duración contacto piel con piel (min)'),
        ),
        migrations.AddField(
            model_name='parto',
            name='eclampsia',
            field=models.BooleanField(default=False, verbose_name='Eclampsia'),
        ),
        migrations.AddField(
            model_name='parto',
            name='edad_materna_parto',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Edad materna al parto'),
        ),
        migrations.AddField(
            model_name='parto',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AddField(
            model_name='parto',
            name='hepatitis_b_positivo',
            field=models.BooleanField(default=False, verbose_name='Hepatitis B positivo'),
        ),
        migrations.AddField(
            model_name='parto',
            name='infeccion_ovular',
            field=models.BooleanField(default=False, verbose_name='Infección ovular'),
        ),
        migrations.AddField(
            model_name='parto',
            name='lactancia_primera_hora',
            field=models.BooleanField(default=False, verbose_name='Lactancia en primera hora'),
        ),
        migrations.AddField(
            model_name='parto',
            name='ligadura_tardia_cordon',
            field=models.BooleanField(default=False, verbose_name='Ligadura tardía del cordón'),
        ),
        migrations.AddField(
            model_name='parto',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='parto',
            name='paridad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Paridad'),
        ),
        migrations.AddField(
            model_name='parto',
            name='preeclampsia_severa',
            field=models.BooleanField(default=False, verbose_name='Preeclampsia severa'),
        ),
        migrations.AddField(
            model_name='parto',
            name='sepsis',
            field=models.BooleanField(default=False, verbose_name='Sepsis'),
        ),
        migrations.AddField(
            model_name='parto',
            name='vdrl_positivo',
            field=models.BooleanField(default=False, verbose_name='VDRL positivo'),
        ),
        migrations.AddField(
            model_name='parto',
            name='vih_positivo',
            field=models.BooleanField(default=False, verbose_name='VIH positivo'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apgar1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR al minuto 1'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apgar5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR al minuto 5'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='diagnostico_alta',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diagnóstico de alta'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='edad_gestacional_semanas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='Edad gestacional (semanas)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='malformacion_detalle',
            field=models.TextField(blank=True, verbose_name='Detalle malformación'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='perimetro_cefalico_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Perímetro cefálico (cm)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='reanimacion',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Básica', 'Básica'), ('Avanzada', 'Avanzada')], default='Ninguna', max_length=15, verbose_name='Reanimación'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='tiene_malformacion',
            field=models.BooleanField(default=False, verbose_name='Presenta malformación'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='condicion_egreso',
            field=models.TextField(verbose_name='Condición al egreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltera', 'Soltera'), ('casada', 'Casada'), ('viuda', 'Viuda'), ('divorciada', 'Divorciada'), ('conviviente', 'Conviviente'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('chilena', 'Chilena'), ('extranjera', 'Extranjera')], default='chilena', help_text='Campo legado. Se recomienda usar el catálogo de nacionalidades.', max_length=20, verbose_name='Nacionalidad (histórica)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nivel_educacional',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('basica', 'Básica'), ('media', 'Media'), ('tecnica', 'Técnica'), ('universitaria', 'Universitaria'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Nivel educacional'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pueblo_originario',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('mapuche', 'Mapuche'), ('aymara', 'Aymara'), ('rapanui', 'Rapa Nui'), ('otro', 'Otro')], default='ninguno', help_text='Campo legado. Se mantendrá hasta migrar completamente al catálogo REM.', max_length=20, verbose_name='Pueblo originario (histórico)'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.CharField(choices=[('vaginal', 'Vaginal'), ('cesarea', 'Cesárea'), ('instrumental', 'Instrumental'), ('otro', 'Otro')], default='vaginal', help_text='Campo legado. Se mantendrá hasta migrar completamente al catálogo REM.', max_length=20, verbose_name='Tipo de parto (histórico)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='identificador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Identificador interno'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='parto',
            field=models.ForeignKey(db_column='episodio_parto_id', on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='clinica.parto', verbose_name='Episodio de parto'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso_gramos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(6500)], verbose_name='Peso (g)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddIndex(
            model_name='reciennacido',
            index=models.Index(fields=['peso_gramos'], name='idx_rn_peso'),
        ),
        migrations.AddIndex(
            model_name='reciennacido',
            index=models.Index(fields=['edad_gestacional_semanas'], name='idx_rn_edad_gest'),
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['activo'], name='idx_consultorio_activo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consultorio',
            field=models.ForeignKey(blank=True, db_column='consultorio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='clinica.consultorio', verbose_name='Consultorio de referencia'),
        ),
        migrations.AddField(
            model_name='eventoclinicorn',
            name='recien_nacido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_clinicos', to='clinica.reciennacido', verbose_name='Recién nacido'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad_catalogo',
            field=models.ForeignKey(blank=True, db_column='nacionalidad_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='clinica.nacionalidad', verbose_name='Nacionalidad (catálogo)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pueblo_originario_catalogo',
            field=models.ForeignKey(blank=True, db_column='pueblo_originario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='clinica.pueblooriginario', verbose_name='Pueblo originario (catálogo)'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_nacimiento'], name='idx_paciente_fecha_nac'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nombres', 'apellido_paterno'], name='idx_paciente_nombre'),
        ),
        migrations.AddField(
            model_name='parto',
            name='tipo_parto_catalogo',
            field=models.ForeignKey(blank=True, db_column='tipo_parto_id', help_text='Referencia a catálogo nacional de tipos de parto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios', to='clinica.tipoparto', verbose_name='Tipo de parto'),
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['fecha_hora'], name='idx_parto_fecha'),
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['paciente'], name='idx_parto_paciente'),
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['edad_materna_parto'], name='idx_parto_edad_materna'),
        ),
        migrations.AddConstraint(
            model_name='eventoclinicorn',
            constraint=models.UniqueConstraint(fields=('recien_nacido', 'tipo_evento'), name='uq_evento_por_rn'),
        ),
    ]
